name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dockmzwili/mzwilicoding-react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dockmzwili/mzwilicoding-react-test npm test

      # Build images with the correct tag
      - run: docker build -t dockmzwili/mzwilicoding-client ./client
      - run: docker build -t dockmzwili/mzwilicoding-nginx ./nginx
      - run: docker build -t dockmzwili/mzwilicoding-server ./server
      - run: docker build -t dockmzwili/mzwilicoding-worker ./worker

      # Push images with the correct tag
      - run: docker push dockmzwili/mzwilicoding-client:latest
      - run: docker push dockmzwili/mzwilicoding-nginx:latest
      - run: docker push dockmzwili/mzwilicoding-server:latest
      - run: docker push dockmzwili/mzwilicoding-worker:latest

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container-docker
          environment_name: Multi-container-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-327910225119
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
